In [79]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix

In [15]:
df=pd.read_csv('iris.csv')
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [16]:
df=df.drop_duplicates()
df=df.dropna(axis=1, how='all')
df=df.dropna(axis=0, how='all')
df=df.loc[:,~df.columns.duplicated()]
df

sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[147 rows x 5 columns]

In [53]:

X=df[['sepal_length', 'sepal_width', 'petal_length','petal_width']]
y=df['species']


sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[147 rows x 4 columns]

In [54]:
#normalization
S=MinMaxScaler()
X_scaled= S.fit_transform(X)

L=LabelEncoder()
Y_encoded = L.fit_transform(y)


array([[0.22222222, 0.625     , 0.06779661, 0.04166667],
       [0.16666667, 0.41666667, 0.06779661, 0.04166667],
       [0.11111111, 0.5       , 0.05084746, 0.04166667],
       [0.08333333, 0.45833333, 0.08474576, 0.04166667],
       [0.19444444, 0.66666667, 0.06779661, 0.04166667],
       [0.30555556, 0.79166667, 0.11864407, 0.125     ],
       [0.08333333, 0.58333333, 0.06779661, 0.08333333],
       [0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.02777778, 0.375     , 0.06779661, 0.04166667],
       [0.16666667, 0.45833333, 0.08474576, 0.        ],
       [0.30555556, 0.70833333, 0.08474576, 0.04166667],
       [0.13888889, 0.58333333, 0.10169492, 0.04166667],
       [0.13888889, 0.41666667, 0.06779661, 0.        ],
       [0.        , 0.41666667, 0.01694915, 0.        ],
       [0.41666667, 0.83333333, 0.03389831, 0.04166667],
       [0.38888889, 1.        , 0.08474576, 0.125     ],
       [0.30555556, 0.79166667, 0.05084746, 0.125     ],
       [0.22222222, 0.625     ,

In [61]:
#test_train_split

X_train, X_test, y_train, y_test= train_test_split(X_scaled, Y_encoded, test_size=0.2, random_state=21)
X_test

array([[0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.36111111, 0.375     , 0.44067797, 0.5       ],
       [0.30555556, 0.58333333, 0.11864407, 0.04166667],
       [0.36111111, 0.20833333, 0.49152542, 0.41666667],
       [0.5       , 0.25      , 0.77966102, 0.54166667],
       [0.22222222, 0.75      , 0.10169492, 0.04166667],
       [0.22222222, 0.75      , 0.08474576, 0.08333333],
       [0.41666667, 0.29166667, 0.52542373, 0.375     ],
       [0.66666667, 0.41666667, 0.6779661 , 0.66666667],
       [0.38888889, 0.25      , 0.42372881, 0.375     ],
       [0.33333333, 0.20833333, 0.50847458, 0.5       ],
       [0.19444444, 0.58333333, 0.10169492, 0.125     ],
       [0.94444444, 0.75      , 0.96610169, 0.875     ],
       [0.22222222, 0.75      , 0.15254237, 0.125     ],
       [0.22222222, 0.70833333, 0.08474576, 0.125     ],
       [0.19444444, 0.625     , 0.10169492, 0.20833333],
       [1.        , 0.75      , 0.91525424, 0.79166667],
       [0.41666667, 0.83333333,

In [62]:
#regression

classification_model=LogisticRegression()
classification_model.fit(X_train, y_train)


LogisticRegression()

In [63]:
X_test

array([[0.19444444, 0.58333333, 0.08474576, 0.04166667],
       [0.36111111, 0.375     , 0.44067797, 0.5       ],
       [0.30555556, 0.58333333, 0.11864407, 0.04166667],
       [0.36111111, 0.20833333, 0.49152542, 0.41666667],
       [0.5       , 0.25      , 0.77966102, 0.54166667],
       [0.22222222, 0.75      , 0.10169492, 0.04166667],
       [0.22222222, 0.75      , 0.08474576, 0.08333333],
       [0.41666667, 0.29166667, 0.52542373, 0.375     ],
       [0.66666667, 0.41666667, 0.6779661 , 0.66666667],
       [0.38888889, 0.25      , 0.42372881, 0.375     ],
       [0.33333333, 0.20833333, 0.50847458, 0.5       ],
       [0.19444444, 0.58333333, 0.10169492, 0.125     ],
       [0.94444444, 0.75      , 0.96610169, 0.875     ],
       [0.22222222, 0.75      , 0.15254237, 0.125     ],
       [0.22222222, 0.70833333, 0.08474576, 0.125     ],
       [0.19444444, 0.625     , 0.10169492, 0.20833333],
       [1.        , 0.75      , 0.91525424, 0.79166667],
       [0.41666667, 0.83333333,

In [66]:
#prediction
y_pred=classification_model.predict(X_test)
y_pred

array([0, 1, 0, 1, 1, 0, 0, 1, 2, 1, 1, 0, 2, 0, 0, 0, 2, 0, 2, 0, 1, 2,
       1, 0, 1, 0, 2, 2, 0, 1])

In [77]:
AC=accuracy_score(y_test,y_pred)
print('AccuRACY score : ', AC)



AccuRACY score :  0.9333333333333333


In [81]:
cm=confusion_matrix(y_test, y_pred)
cm

array([[13,  0,  0],
       [ 0,  9,  1],
       [ 0,  1,  6]], dtype=int64)

In [70]:
y_pred_names=L.inverse_transform(y_pred)
y_pred_names

array(['setosa', 'versicolor', 'setosa', 'versicolor', 'versicolor',
       'setosa', 'setosa', 'versicolor', 'virginica', 'versicolor',
       'versicolor', 'setosa', 'virginica', 'setosa', 'setosa', 'setosa',
       'virginica', 'setosa', 'virginica', 'setosa', 'versicolor',
       'virginica', 'versicolor', 'setosa', 'versicolor', 'setosa',
       'virginica', 'virginica', 'setosa', 'versicolor'], dtype=object)