In [50]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix



In [51]:
df=pd.read_csv('linear_reg.csv')
df

X           Y
0      1    3.888889
1      2    4.555556
2      3    5.222222
3      4    5.888889
4      5    6.555556
..   ...         ...
295  296  200.555556
296  297  201.222222
297  298  201.888889
298  299    1.888889
299  300    1.888889

[300 rows x 2 columns]

In [168]:
x=df['X'].values.reshape(-1, 1)
print(x)
y=df['Y'].values.reshape(-1, 1)
print(y)

[[  1]
 [  2]
 [  3]
 [  4]
 [  5]
 [  6]
 [  7]
 [  8]
 [  9]
 [ 10]
 [ 11]
 [ 12]
 [ 13]
 [ 14]
 [ 15]
 [ 16]
 [ 17]
 [ 18]
 [ 19]
 [ 20]
 [ 21]
 [ 22]
 [ 23]
 [ 24]
 [ 25]
 [ 26]
 [ 27]
 [ 28]
 [ 29]
 [ 30]
 [ 31]
 [ 32]
 [ 33]
 [ 34]
 [ 35]
 [ 36]
 [ 37]
 [ 38]
 [ 39]
 [ 40]
 [ 41]
 [ 42]
 [ 43]
 [ 44]
 [ 45]
 [ 46]
 [ 47]
 [ 48]
 [ 49]
 [ 50]
 [ 51]
 [ 52]
 [ 53]
 [ 54]
 [ 55]
 [ 56]
 [ 57]
 [ 58]
 [ 59]
 [ 60]
 [ 61]
 [ 62]
 [ 63]
 [ 64]
 [ 65]
 [ 66]
 [ 67]
 [ 68]
 [ 69]
 [ 70]
 [ 71]
 [ 72]
 [ 73]
 [ 74]
 [ 75]
 [ 76]
 [ 77]
 [ 78]
 [ 79]
 [ 80]
 [ 81]
 [ 82]
 [ 83]
 [ 84]
 [ 85]
 [ 86]
 [ 87]
 [ 88]
 [ 89]
 [ 90]
 [ 91]
 [ 92]
 [ 93]
 [ 94]
 [ 95]
 [ 96]
 [ 97]
 [ 98]
 [ 99]
 [100]
 [101]
 [102]
 [103]
 [104]
 [105]
 [106]
 [107]
 [108]
 [109]
 [110]
 [111]
 [112]
 [113]
 [114]
 [115]
 [116]
 [117]
 [118]
 [119]
 [120]
 [121]
 [122]
 [123]
 [124]
 [125]
 [126]
 [127]
 [128]
 [129]
 [130]
 [131]
 [132]
 [133]
 [134]
 [135]
 [136]
 [137]
 [138]
 [139]
 [140]
 [141]
 [142]
 [143]

In [169]:
model = LinearRegression()
model.fit(x,y)

LinearRegression()

In [171]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.3, random_state = 20)
x_train, x_test, y_train, y_test

(array([[122],
        [ 60],
        [109],
        [265],
        [113],
        [271],
        [141],
        [ 16],
        [130],
        [258],
        [193],
        [227],
        [241],
        [261],
        [121],
        [289],
        [  6],
        [ 22],
        [174],
        [  2],
        [134],
        [ 95],
        [100],
        [178],
        [206],
        [269],
        [247],
        [ 88],
        [175],
        [ 67],
        [194],
        [ 45],
        [104],
        [125],
        [ 81],
        [274],
        [ 74],
        [171],
        [262],
        [282],
        [164],
        [278],
        [287],
        [ 51],
        [170],
        [ 47],
        [146],
        [ 65],
        [186],
        [135],
        [218],
        [228],
        [257],
        [277],
        [ 12],
        [136],
        [155],
        [  3],
        [ 77],
        [ 68],
        [211],
        [107],
        [112],
        [ 32],
        [ 97],
        [ 75],
        [2

In [172]:
model.fit(x,y)

LinearRegression()

In [173]:
model.predict(x_test)

array([[141.57831626],
       [196.62217675],
       [ 24.4501015 ],
       [188.94163808],
       [ 91.01477   ],
       [131.33759803],
       [ 52.61207663],
       [159.49957317],
       [ 45.57158285],
       [ 69.25324376],
       [133.2577327 ],
       [ 76.29373754],
       [111.49620646],
       [139.65818159],
       [162.05975272],
       [192.14186253],
       [191.50181764],
       [146.69867538],
       [195.98213186],
       [ 82.69418643],
       [108.9360269 ],
       [ 66.05301931],
       [169.10024651],
       [ 46.21162774],
       [ 63.49283975],
       [160.77966295],
       [181.9011443 ],
       [123.65705936],
       [ 81.41409666],
       [ 36.61095439],
       [ 40.45122373],
       [115.97652068],
       [ 75.01364776],
       [ 64.13288464],
       [ 19.32974238],
       [ 59.65257041],
       [148.61881005],
       [ 11.00915882],
       [ 76.93378243],
       [ 16.76956282],
       [112.13625135],
       [162.69979761],
       [101.25548823],
       [ 27

In [174]:
model.score(x,y)

0.9213615685311795

In [175]:
z= 3.76
x=[3.76]
for i in range(49):
    z=z+0.05
    x.append(z)
x=np.round(x,2)
x

array([3.76, 3.81, 3.86, 3.91, 3.96, 4.01, 4.06, 4.11, 4.16, 4.21, 4.26,
       4.31, 4.36, 4.41, 4.46, 4.51, 4.56, 4.61, 4.66, 4.71, 4.76, 4.81,
       4.86, 4.91, 4.96, 5.01, 5.06, 5.11, 5.16, 5.21, 5.26, 5.31, 5.36,
       5.41, 5.46, 5.51, 5.56, 5.61, 5.66, 5.71, 5.76, 5.81, 5.86, 5.91,
       5.96, 6.01, 6.06, 6.11, 6.16, 6.21])

In [176]:
b=np.arange(5)
b.fill(0)
a=np.arange(20)
a.fill(1)
c=np.arange(25)
c.fill(0)
y=np.concatenate((b, a, c))
y

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

In [180]:
x
x=x.reshape(-1,1)
print(x)
y
y=y.reshape(-1,1)
print(y)

[[3.76]
 [3.81]
 [3.86]
 [3.91]
 [3.96]
 [4.01]
 [4.06]
 [4.11]
 [4.16]
 [4.21]
 [4.26]
 [4.31]
 [4.36]
 [4.41]
 [4.46]
 [4.51]
 [4.56]
 [4.61]
 [4.66]
 [4.71]
 [4.76]
 [4.81]
 [4.86]
 [4.91]
 [4.96]
 [5.01]
 [5.06]
 [5.11]
 [5.16]
 [5.21]
 [5.26]
 [5.31]
 [5.36]
 [5.41]
 [5.46]
 [5.51]
 [5.56]
 [5.61]
 [5.66]
 [5.71]
 [5.76]
 [5.81]
 [5.86]
 [5.91]
 [5.96]
 [6.01]
 [6.06]
 [6.11]
 [6.16]
 [6.21]]
[[0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [178]:
model = LogisticRegression()
model.fit(x,y)

C:\Users\HP\anaconda3\lib\site-packages\sklearn\utils\validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LogisticRegression()

In [179]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state = 20)
x_train, x_test, y_train, y_test

(array([[5.76],
        [4.61],
        [4.66],
        [3.76],
        [5.11],
        [5.41],
        [5.56],
        [5.86],
        [4.26],
        [3.91],
        [5.81],
        [4.41],
        [6.06],
        [3.86],
        [5.66],
        [5.71],
        [4.01],
        [5.91],
        [5.61],
        [5.26],
        [4.06],
        [5.21],
        [4.56],
        [4.71],
        [6.21],
        [5.96],
        [4.81],
        [5.36],
        [5.46],
        [4.11],
        [4.86],
        [4.31],
        [4.76],
        [4.21],
        [6.16],
        [5.16],
        [5.31],
        [4.51],
        [5.06],
        [5.51]]),
 array([[4.36],
        [4.46],
        [3.96],
        [4.16],
        [6.01],
        [3.81],
        [5.01],
        [4.96],
        [6.11],
        [4.91]]),
 array([[0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [0],
        [0],
        [0],
 

In [188]:
model.predict(x_test)

array([1, 1, 1, 1, 0, 1, 0, 0, 0, 0])

In [191]:
model.score(x_train,y_train)

0.8

In [193]:
cm=confusion_matrix(y_test,model.predict(x_test))
cm

array([[3, 2],
       [2, 3]], dtype=int64)